### ISSUE TITLE
can not  deploy to mvm network

### ISSUE THREAD

**Issue by luozhanxin** [MixinNetwork/mvm-contracts#5]
When I try to deploy the Counter.sol contract using this project, it sendTransaction to mvm，and it return txhash, but Unable to find transaction records on the blockchain explorer.

eth_sendTransaction params
```yaml
[
  {
    gas: '0x1cbd5',
    from: '0x897d1d92dd90b6ad73ee7ea9a13f360a5421c61b',
    data: '0x********',
    maxFeePerGas: '0x8',
    maxPriorityFeePerGas: '0x0'
  }
]
```

hardhat.config.js
![Screenshot 2023-06-12 at 18 12 33](https://github.com/MixinNetwork/mvm-contracts/assets/16456918/91564a5d-20b7-43f6-bcdf-d1136e907af1)
